typography_spectrum: 0.21538795670494437
color:
  brandStrength: 0.413399362238124
  lightness: 0.5010368512012064
  saturation: 0.5465056363027543
  rhythmicContrast: 0.4161839138250798
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.5507595748640597
name: Anie's Corner
navigation:
  - name: Books
    url: 'https://thegrid.ai/anies-corner-books'
    type: external
title: Welcome to Anie's Corner
description: Tagline
